# Site settings
permalink: /posts/:title
name: ar7z1
author: Artem Zinenko
email: zinenkoartem@gmail.com
description: Спецкурс "Распределенные системы"
baseurl: "/courses" # the subpath of your site, e.g. /blog/
twitter_username: ar7z1
github_username:  ar7z1
lsi: false
exclude: [Gemfile]
timezone: Asia/Yekaterinburg
markdown: kramdown
highlighter: pygments
gems:
  - jemoji
